language: cpp
compiler: g++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8.1.0
      env:
         - MATRIX_EVAL="CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
  - mkdir lib; sh lapack_install.sh

script:
  - make
