#sudo: false

language: cpp
compiler: g++
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-cache search gfortran
  - sudo apt-get install g++-5
  - sudo apt-get install gcc-5
  - sudo apt-get install gfortran-5
  - sudo apt-get install libgfortran-5-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
#  - mkdir lib; sh lapack_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - g++-5
      - gcc-5
      - gfortran-5
      
script:
  - gcc --version
  - g++ --version
  - which gfortran
  - locate libgfortran
  - make CXX="${CXX}"

notifications:
  email: false
