#sudo: false

language: cpp
compiler: g++
dist: trusty
notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - g++-5
      - gcc-5
      - gfortran-5
      - libgfortran-5-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - git clone https://github.com/soedinglab/MMseqs2.git
  - cd MMseqs2
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=. ..
  - make
  - make install 
  - export PATH=$(pwd)/bin/:$PATH
  - cd ..
  - cd ..
  - mkdir lib; sh lapack_install.sh
  - make CXX="${CXX}"

script:
  - ./gsep -h
  
