sudo: false

language: cpp
compiler: g++
dist: trusty
notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - libgfortran-5-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 90
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - make CXX="${CXX}"
  - export PATH=$(pwd)/MMseqs2/build/bin:$PATH
  - ls lib

script:
  - ./gs2 -e100 -t 1 -r 12345 example/200.faa
